"""Optimization tips router — cost/prompt-shape advice generated by the
optimization_tips scheduled job (app/services/optimization/), which
evaluates app/services/optimization/rules/* daily.
"""
from datetime import date
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.core.deps import get_db
from app.models import OptimizationTip, Organization, Project

router = APIRouter(prefix="/optimization-tips", tags=["optimization-tips"])


def _serialize(*, tip: OptimizationTip, org_name: Optional[str], project_name: Optional[str]) -> dict:
    return {
        "id": tip.id,
        "org_id": tip.org_id,
        "org_name": org_name or tip.org_id,
        "project_id": tip.project_id,
        "project_name": project_name or tip.project_id,
        "model_name": tip.model_name,
        "tip_type": tip.tip_type,
        "severity": tip.severity,
        "title": tip.title,
        "message": tip.message,
        "estimated_monthly_savings": (
            float(tip.estimated_monthly_savings) if tip.estimated_monthly_savings is not None else 0.0
        ),
        "confidence": tip.confidence,
        "evidence_json": tip.evidence_json,
        "status": tip.status,
        "period_start": tip.period_start.isoformat() if tip.period_start else None,
        "period_end": tip.period_end.isoformat() if tip.period_end else None,
        "created_at": tip.created_at.isoformat() if tip.created_at else None,
    }


def _enrich(*, db: Session, tips: list[OptimizationTip]) -> list[dict]:
    if not tips:
        return []

    org_ids = {t.org_id for t in tips if t.org_id}
    project_ids = {t.project_id for t in tips if t.project_id}

    org_names = {
        o.id: o.org_name
        for o in db.query(Organization).filter(Organization.id.in_(org_ids)).all()
    } if org_ids else {}

    project_names = {
        p.id: p.project_name
        for p in db.query(Project).filter(Project.id.in_(project_ids)).all()
    } if project_ids else {}

    return [
        _serialize(
            tip=t,
            org_name=org_names.get(t.org_id),
            project_name=project_names.get(t.project_id),
        )
        for t in tips
    ]


# ---------------------------------------------------------------------------
# List tips
# ---------------------------------------------------------------------------

@router.get("/")
def list_tips(
    *,
    status: Optional[str] = Query("open"),
    org_id: Optional[str] = Query(None),
    project_id: Optional[str] = Query(None),
    tip_type: Optional[str] = Query(None),
    severity: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=500),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
) -> dict:
    q = db.query(OptimizationTip)
    if status:
        q = q.filter(OptimizationTip.status == status)
    if org_id:
        q = q.filter(OptimizationTip.org_id == org_id)
    if project_id:
        q = q.filter(OptimizationTip.project_id == project_id)
    if tip_type:
        q = q.filter(OptimizationTip.tip_type == tip_type)
    if severity:
        q = q.filter(OptimizationTip.severity == severity)

    total = q.count()
    rows = q.order_by(OptimizationTip.created_at.desc()).offset(offset).limit(limit).all()

    return {"total": total, "offset": offset, "items": _enrich(db=db, tips=rows)}


# ---------------------------------------------------------------------------
# Summary — counts by tip_type + total estimated savings (dashboard header)
# ---------------------------------------------------------------------------

@router.get("/summary")
def tips_summary(
    *,
    org_id: Optional[str] = Query(None),
    project_id: Optional[str] = Query(None),
    db: Session = Depends(get_db),
) -> dict:
    q = db.query(
        OptimizationTip.tip_type,
        func.count(OptimizationTip.id),
        func.sum(OptimizationTip.estimated_monthly_savings),
    ).filter(OptimizationTip.status == "open")
    if org_id:
        q = q.filter(OptimizationTip.org_id == org_id)
    if project_id:
        q = q.filter(OptimizationTip.project_id == project_id)
    rows = q.group_by(OptimizationTip.tip_type).all()

    by_type = {
        tip_type: {"count": count, "estimated_monthly_savings": float(savings or 0)}
        for tip_type, count, savings in rows
    }
    return {
        "by_tip_type": by_type,
        "total_open": sum(v["count"] for v in by_type.values()),
        "total_estimated_monthly_savings": sum(v["estimated_monthly_savings"] for v in by_type.values()),
    }


# ---------------------------------------------------------------------------
# Dismiss / apply
# ---------------------------------------------------------------------------

@router.patch("/{tip_id}/dismiss")
def dismiss_tip(
    *,
    tip_id: int,
    db: Session = Depends(get_db),
) -> dict:
    tip = db.query(OptimizationTip).filter(OptimizationTip.id == tip_id).first()
    if not tip:
        raise HTTPException(status_code=404, detail="Optimization tip not found.")
    tip.status = "dismissed"
    db.commit()
    db.refresh(tip)
    return _enrich(db=db, tips=[tip])[0]


@router.patch("/{tip_id}/apply")
def apply_tip(
    *,
    tip_id: int,
    db: Session = Depends(get_db),
) -> dict:
    tip = db.query(OptimizationTip).filter(OptimizationTip.id == tip_id).first()
    if not tip:
        raise HTTPException(status_code=404, detail="Optimization tip not found.")
    tip.status = "applied"
    db.commit()
    db.refresh(tip)
    return _enrich(db=db, tips=[tip])[0]


# ---------------------------------------------------------------------------
# Manual re-trigger — mirrors POST /summary/admin/rebuild-daily
# ---------------------------------------------------------------------------

@router.post("/admin/rebuild")
def rebuild_tips(
    *,
    window_end: Optional[date] = Query(None),
    db: Session = Depends(get_db),
) -> dict:
    from app.workers.tasks import _generate_optimization_tips

    inserted = _generate_optimization_tips(db=db, window_end=window_end or date.today())
    db.commit()
    return {"inserted": inserted}
