"""Optimization tips router — cost/prompt-shape advice generated by the
optimization_tips scheduled job (app/services/optimization/), which
evaluates app/services/optimization/rules/* daily.

Apply/dismiss both persist real state: dismiss just closes the tip, but
apply additionally writes the governance-rule config that makes the
recommendation take effect on live proxy traffic for tip types where a real
enforcement lever exists (see _apply_tip_action below and
app/services/optimization/enforcement.py, which the proxy consults on every
request). Tip types with no platform-level lever (cache_opportunity,
oversized_prompt) are acknowledged and audited but change no config — the
underlying fix requires a change in the calling application, not something
this proxy can do on its own.
"""
import uuid
from datetime import date
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.core.deps import get_db
from app.models import GovernanceRule, OptimizationTip, Organization, Project
from app.services.audit_service import log_event

router = APIRouter(prefix="/optimization-tips", tags=["optimization-tips"])


def _serialize(*, tip: OptimizationTip, org_name: Optional[str], project_name: Optional[str]) -> dict:
    return {
        "id": tip.id,
        "org_id": tip.org_id,
        "org_name": org_name or tip.org_id,
        "project_id": tip.project_id,
        "project_name": project_name or tip.project_id,
        "model_name": tip.model_name,
        "tip_type": tip.tip_type,
        "severity": tip.severity,
        "title": tip.title,
        "message": tip.message,
        "estimated_monthly_savings": (
            float(tip.estimated_monthly_savings) if tip.estimated_monthly_savings is not None else 0.0
        ),
        "confidence": tip.confidence,
        "evidence_json": tip.evidence_json,
        "status": tip.status,
        "period_start": tip.period_start.isoformat() if tip.period_start else None,
        "period_end": tip.period_end.isoformat() if tip.period_end else None,
        "created_at": tip.created_at.isoformat() if tip.created_at else None,
    }


def _enrich(*, db: Session, tips: list[OptimizationTip]) -> list[dict]:
    if not tips:
        return []

    org_ids = {t.org_id for t in tips if t.org_id}
    project_ids = {t.project_id for t in tips if t.project_id}

    org_names = {
        o.id: o.org_name
        for o in db.query(Organization).filter(Organization.id.in_(org_ids)).all()
    } if org_ids else {}

    project_names = {
        p.id: p.project_name
        for p in db.query(Project).filter(Project.id.in_(project_ids)).all()
    } if project_ids else {}

    return [
        _serialize(
            tip=t,
            org_name=org_names.get(t.org_id),
            project_name=project_names.get(t.project_id),
        )
        for t in tips
    ]


# ---------------------------------------------------------------------------
# List tips
# ---------------------------------------------------------------------------

@router.get("/")
def list_tips(
    *,
    status: Optional[str] = Query("open"),
    org_id: Optional[str] = Query(None),
    project_id: Optional[str] = Query(None),
    tip_type: Optional[str] = Query(None),
    severity: Optional[str] = Query(None),
    limit: int = Query(100, ge=1, le=500),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
) -> dict:
    q = db.query(OptimizationTip)
    if status:
        q = q.filter(OptimizationTip.status == status)
    if org_id:
        q = q.filter(OptimizationTip.org_id == org_id)
    if project_id:
        q = q.filter(OptimizationTip.project_id == project_id)
    if tip_type:
        q = q.filter(OptimizationTip.tip_type == tip_type)
    if severity:
        q = q.filter(OptimizationTip.severity == severity)

    total = q.count()
    rows = q.order_by(OptimizationTip.created_at.desc()).offset(offset).limit(limit).all()

    return {"total": total, "offset": offset, "items": _enrich(db=db, tips=rows)}


# ---------------------------------------------------------------------------
# Summary — counts by tip_type + total estimated savings (dashboard header)
# ---------------------------------------------------------------------------

@router.get("/summary")
def tips_summary(
    *,
    org_id: Optional[str] = Query(None),
    project_id: Optional[str] = Query(None),
    db: Session = Depends(get_db),
) -> dict:
    q = db.query(
        OptimizationTip.tip_type,
        func.count(OptimizationTip.id),
        func.sum(OptimizationTip.estimated_monthly_savings),
    ).filter(OptimizationTip.status == "open")
    if org_id:
        q = q.filter(OptimizationTip.org_id == org_id)
    if project_id:
        q = q.filter(OptimizationTip.project_id == project_id)
    rows = q.group_by(OptimizationTip.tip_type).all()

    by_type = {
        tip_type: {"count": count, "estimated_monthly_savings": float(savings or 0)}
        for tip_type, count, savings in rows
    }
    return {
        "by_tip_type": by_type,
        "total_open": sum(v["count"] for v in by_type.values()),
        "total_estimated_monthly_savings": sum(v["estimated_monthly_savings"] for v in by_type.values()),
    }


# ---------------------------------------------------------------------------
# Dismiss / apply
# ---------------------------------------------------------------------------

def _upsert_scoped_rule(
    *,
    db: Session,
    org_id: str,
    project_id: Optional[str],
    metric_name: str,
    scope_reference: str,
    threshold_value: float = 0,
    redirect_target_model: Optional[str] = None,
    severity: str = "low",
) -> GovernanceRule:
    """One active row per (org, project, metric_name, scope_reference) — same
    replace-on-reapply pattern as model_selection_service.set_allowed_models."""
    scope_level = "organization" if project_id is None else "project"
    db.query(GovernanceRule).filter(
        GovernanceRule.org_id == org_id,
        GovernanceRule.project_id == project_id,
        GovernanceRule.metric_name == metric_name,
        GovernanceRule.scope_reference == scope_reference,
    ).delete(synchronize_session=False)
    rule = GovernanceRule(
        rule_name=(
            f"{metric_name}:{scope_level}:{org_id}:{project_id or '-'}:"
            f"{scope_reference}:{uuid.uuid4().hex[:8]}"
        ),
        metric_name=metric_name,
        operator="=",
        threshold_value=threshold_value,
        severity=severity,
        scope_level=scope_level,
        scope_reference=scope_reference,
        is_active=True,
        org_id=org_id,
        project_id=project_id,
        redirect_target_model=redirect_target_model,
    )
    db.add(rule)
    db.flush()
    return rule


def _apply_tip_action(*, db: Session, tip: OptimizationTip) -> str:
    """Make the tip's recommendation take effect where a real enforcement
    lever exists; otherwise just describe why it can't be automated. Returns
    a human-readable summary used for both the audit log and the API
    response. Raises HTTPException(400) if the tip lacks the data needed to
    act (e.g. a legacy tip created before evidence carried a concrete
    target — dismiss it and let the next rebuild produce an actionable one)."""
    scope = f"project '{tip.project_id}'" if tip.project_id else "the whole org"
    params = (tip.evidence_json or {}).get("params", {})

    if tip.tip_type == "model_substitution":
        from_model = params.get("from_model") or tip.model_name
        to_model = params.get("to_model")
        if not from_model or not to_model:
            raise HTTPException(
                status_code=400,
                detail="Tip is missing from/to model data — rebuild tips and retry.",
            )
        _upsert_scoped_rule(
            db=db, org_id=tip.org_id, project_id=tip.project_id,
            metric_name="model_redirect", scope_reference=from_model,
            redirect_target_model=to_model, severity="medium",
        )
        return f"All future requests for '{from_model}' in {scope} will now be served by '{to_model}'."

    if tip.tip_type in ("response_length", "response_truncated"):
        model = tip.model_name or params.get("model")
        suggested = params.get("suggested_max_tokens")
        if not model or not suggested:
            raise HTTPException(
                status_code=400,
                detail=(
                    "This tip predates automatic max_tokens enforcement — dismiss it and "
                    "trigger a rebuild (POST /optimization-tips/admin/rebuild) to get an "
                    "actionable tip."
                ),
            )
        is_cap = tip.tip_type == "response_length"
        _upsert_scoped_rule(
            db=db, org_id=tip.org_id, project_id=tip.project_id,
            metric_name="optimization_max_tokens_cap" if is_cap else "optimization_max_tokens_floor",
            scope_reference=model, threshold_value=suggested, severity="low",
        )
        verb = "capped at" if is_cap else "raised to at least"
        return f"max_tokens for '{model}' in {scope} will now be {verb} {suggested} tokens."

    return (
        "Marked as acted on. This recommendation requires a change in your application code "
        "(prompt caching / conversation-history trimming) — it isn't something the platform "
        "can apply on your behalf."
    )


def _audit_tip_action(*, db: Session, tip: OptimizationTip, action: str, summary: str) -> None:
    log_event(
        db,
        org_id=tip.org_id,
        project_id=tip.project_id,
        audit_category="optimization",
        audit_action=action,
        actor_type="user",
        entity_type="optimization_tip",
        entity_id=str(tip.id),
        old_value={"status": "open"},
        new_value={"status": tip.status},
        change_summary=summary,
        metadata={"tip_type": tip.tip_type, "model_name": tip.model_name},
        flush=False,
    )


@router.patch("/{tip_id}/dismiss")
def dismiss_tip(
    *,
    tip_id: int,
    db: Session = Depends(get_db),
) -> dict:
    tip = db.query(OptimizationTip).filter(OptimizationTip.id == tip_id).first()
    if not tip:
        raise HTTPException(status_code=404, detail="Optimization tip not found.")
    if tip.status != "open":
        raise HTTPException(status_code=400, detail=f"Tip is already '{tip.status}'.")
    tip.status = "dismissed"
    _audit_tip_action(db=db, tip=tip, action="tip_dismissed", summary=f"Tip #{tip.id} ({tip.tip_type}) dismissed.")
    db.commit()
    db.refresh(tip)
    return _enrich(db=db, tips=[tip])[0]


@router.patch("/{tip_id}/apply")
def apply_tip(
    *,
    tip_id: int,
    db: Session = Depends(get_db),
) -> dict:
    tip = db.query(OptimizationTip).filter(OptimizationTip.id == tip_id).first()
    if not tip:
        raise HTTPException(status_code=404, detail="Optimization tip not found.")
    if tip.status != "open":
        raise HTTPException(status_code=400, detail=f"Tip is already '{tip.status}'.")

    summary = _apply_tip_action(db=db, tip=tip)
    tip.status = "applied"
    _audit_tip_action(db=db, tip=tip, action="tip_applied", summary=summary)
    db.commit()
    db.refresh(tip)

    result = _enrich(db=db, tips=[tip])[0]
    result["applied_summary"] = summary
    return result


# ---------------------------------------------------------------------------
# Manual re-trigger — mirrors POST /summary/admin/rebuild-daily
# ---------------------------------------------------------------------------

@router.post("/admin/rebuild")
def rebuild_tips(
    *,
    window_end: Optional[date] = Query(None),
    db: Session = Depends(get_db),
) -> dict:
    from app.workers.tasks import _generate_optimization_tips

    inserted = _generate_optimization_tips(db=db, window_end=window_end or date.today())
    db.commit()
    return {"inserted": inserted}
